//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_type
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public Nullable<double> ScrapRate { get; set; }
    }
}
