//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorAPP
{
    using MasterFloorAPP.Pages;
    using System;
    using System.Collections.Generic;

    public partial class Partner_products
    {
        public int ID { get; set; }
        public int Product { get; set; }
        public int Partner { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> SaleDATE { get; set; }
        public Nullable<decimal> Discount { get; set; }

        public virtual Partner Partner1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
